name: Validate Regex

on:
  push:
    paths:
      - "regex_patterns/**/*.yml"
      - "regex_patterns/**/*.yaml"
      - ".github/workflows/validateRegex.yml"
      - "scripts/validatePattern.ps1"
      - "scripts/validateAllPatterns.ps1"
  pull_request:
    paths:
      - "regex_patterns/**/*.yml"
      - "regex_patterns/**/*.yaml"
      - ".github/workflows/validateRegex.yml"
      - "scripts/validatePattern.ps1"
      - "scripts/validateAllPatterns.ps1"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell:lts
    steps:
      - uses: actions/checkout@v4

      - name: Validate Patterns
        run: pwsh scripts/validatePatterns.ps1
